In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.linear_model import LinearRegression

# Using Linear SVM

In [3]:
dataset = pd.read_csv('todayTask/heart.csv')
dataset.corr()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
age,1.000000,-0.098447,-0.068653,0.279351,0.213678,0.121308,-0.116211,-0.398522,0.096801,0.210013,-0.168814,0.276326,0.068001,-0.225439
sex,-0.098447,1.000000,-0.049353,-0.056769,-0.197912,0.045032,-0.058196,-0.044020,0.141664,0.096093,-0.030711,0.118261,0.210041,-0.280937
cp,-0.068653,-0.049353,1.000000,0.047608,-0.076904,0.094444,0.044421,0.295762,-0.394280,-0.149230,0.119717,-0.181053,-0.161736,0.433798
trestbps,0.279351,-0.056769,0.047608,1.000000,0.123174,0.177531,-0.114103,-0.046698,0.067616,0.193216,-0.121475,0.101389,0.062210,-0.144931
chol,0.213678,-0.197912,-0.076904,0.123174,1.000000,0.013294,-0.151040,-0.009940,0.067023,0.053952,-0.004038,0.070511,0.098803,-0.085239
fbs,0.121308,0.045032,0.094444,0.177531,0.013294,1.000000,-0.084189,-0.008567,0.025665,0.005747,-0.059894,0.137979,-0.032019,-0.028046
restecg,-0.116211,-0.058196,0.044421,-0.114103,-0.151040,-0.084189,1.000000,0.044123,-0.070733,-0.058770,0.093045,-0.072042,-0.011981,0.137230
thalach,-0.398522,-0.044020,0.295762,-0.046698,-0.009940,-0.008567,0.044123,1.000000,-0.378812,-0.344187,0.386784,-0.213177,-0.096439,0.421741
exang,0.096801,0.141664,-0.394280,0.067616,0.067023,0.025665,-0.070733,-0.378812,1.000000,0.288223,-0.257748,0.115739,0.206754,-0.436757
oldpeak,0.210013,0.096093,-0.149230,0.193216,0.053952,0.005747,-0.058770,-0.344187,0.288223,1.000000,-0.577537,0.222682,0.210244,-0.430696
slope,-0.168814,-0.030711,0.119717,-0.121475,-0.004038,-0.059894,0.093045,0.386784,-0.257748,-0.577537,1.000000,-0.080155,-0.104764,0.345877
ca,0.276326,0.118261,-0.181053,0.101389,0.070511,0.137979,-0.072042,-0.213177,0.115739,0.222682,-0.080155,1.000000,0.151832,-0.391724
thal,0.068001,0.210041,-0.161736,0.062210,0.098803,-0.032019,-0.011981,-0.096439,0.206754,0.210244,-0.104764,0.151832,1.000000,-0.344029
target,-0.225439,-0.280937,0.433798,-0.144931,-0.085239,-0.028046,0.137230,0.421741,-0.436757,-0.430696,0.345877,-0.391724,-0.344029,1.000000

In [4]:
features = dataset.iloc[:,0:-1].values
goal = dataset.iloc[:,-1].values

# standrize the values
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
features = scaler.fit_transform(features)

In [5]:
#import seaborn as sns
#df = pd.DataFrame({'Age':features[:,2] , 'Goal':features[:,5]})
#sns.lmplot(x='Age', y='Goal', data=df,
#            fit_reg=False );

In [6]:
# split into train and test
from sklearn.model_selection import train_test_split
train_set, test_set, goal_train, goal_test = train_test_split(features,goal,test_size =0.25,random_state=0)

In [7]:
from sklearn.svm import SVC
classifier = SVC(kernel ='linear', random_state = 0)
classifier.fit(train_set, goal_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [8]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(goal_test, classifier.predict(test_set))
print(classifier.score(test_set, goal_test))
pd.DataFrame(cm)

0.8552631578947368

    0   1
0  24   9
1   2  41

# using KNN

In [9]:
from sklearn.neighbors import KNeighborsClassifier
for K in [1, 3, 5, 10, 20, 100, 150, len(train_set)]:
    classifier = KNeighborsClassifier(n_neighbors=K)
    classifier.fit(train_set, goal_train)
    cm = confusion_matrix(goal_test, classifier.predict(test_set))
    print('K = %d\n-------------'%K)
    print(pd.DataFrame(cm))
    print("model accuracy : {:.4f}".format(classifier.score(test_set, goal_test)))
    print('-------------\n\n')

K = 1
-------------
    0   1
0  27   6
1  10  33
model accuracy : 0.7895
-------------


K = 3
-------------
    0   1
0  27   6
1   6  37
model accuracy : 0.8421
-------------


K = 5
-------------
    0   1
0  25   8
1   4  39
model accuracy : 0.8421
-------------


K = 10
-------------
    0   1
0  25   8
1   4  39
model accuracy : 0.8421
-------------


K = 20
-------------
    0   1
0  22  11
1   3  40
model accuracy : 0.8158
-------------


K = 100
-------------
    0   1
0  19  14
1   2  41
model accuracy : 0.7895
-------------


K = 150
-------------
    0   1
0  18  15
1   0  43
model accuracy : 0.8026
-------------


K = 227
-------------
   0   1
0  0  33
1  0  43
model accuracy : 0.5658
-------------

# Using Logistic Reg

In [10]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(random_state = 0)
logistic.fit(train_set, goal_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(goal_test, logistic.predict(test_set))
pd.DataFrame(cm)

    0   1
0  24   9
1   4  39

In [12]:
#%%time
logistic.score(test_set, goal_test)

0.8289473684210527

# Bank

In [28]:
bank = pd.read_csv('todayTask/bank-full.csv' , sep=';')

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
bank.iloc[:,-1] = encoder.fit_transform(bank.iloc[:,-1])
bank.iloc[:,2] = encoder.fit_transform(bank.iloc[:,2])
bank.iloc[:,3] = encoder.fit_transform(bank.iloc[:,3])

bank.corr()

,age,marital,education,balance,day,duration,campaign,pdays,previous,y
age,1.000000,-0.403240,-0.106807,0.097783,-0.009120,-0.004648,0.004760,-0.023758,0.001288,0.025155
marital,-0.403240,1.000000,0.108576,0.002122,-0.005261,0.011852,-0.008994,0.019172,0.014973,0.045588
education,-0.106807,0.108576,1.000000,0.064514,0.022671,0.001935,0.006255,0.000052,0.017570,0.066241
balance,0.097783,0.002122,0.064514,1.000000,0.004503,0.021560,-0.014578,0.003435,0.016674,0.052838
day,-0.009120,-0.005261,0.022671,0.004503,1.000000,-0.030206,0.162490,-0.093044,-0.051710,-0.028348
duration,-0.004648,0.011852,0.001935,0.021560,-0.030206,1.000000,-0.084570,-0.001565,0.001203,0.394521
campaign,0.004760,-0.008994,0.006255,-0.014578,0.162490,-0.084570,1.000000,-0.088628,-0.032855,-0.073172
pdays,-0.023758,0.019172,0.000052,0.003435,-0.093044,-0.001565,-0.088628,1.000000,0.454820,0.103621
previous,0.001288,0.014973,0.017570,0.016674,-0.051710,0.001203,-0.032855,0.454820,1.000000,0.093236
y,0.025155,0.045588,0.066241,0.052838,-0.028348,0.394521,-0.073172,0.103621,0.093236,1.000000

In [29]:
features = bank.iloc[:,[0,2,3,5]].values
goal = bank.iloc[:,-1].values

# standrize the values
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
features = scaler.fit_transform(features)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

In [30]:
# split into train and test
from sklearn.model_selection import train_test_split
train_set, test_set, goal_train, goal_test = train_test_split(features,goal,test_size =0.20,random_state=0)

# Using Linear SVM

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel ='linear', random_state = 0)
classifier.fit(train_set, goal_train)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(goal_test, classifier.predict(test_set))
print(classifier.score(test_set, goal_test))
pd.DataFrame(cm)

0.8824505142098861

      0  1
0  7980  0
1  1063  0

# Using KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
for K in [1, 3, 5, 10, 20, 100, 150, len(test_set)]:
    classifier = KNeighborsClassifier(n_neighbors=K)
    classifier.fit(train_set, goal_train)
    print("model accuracy : {:.4f}".format(classifier.score(test_set, goal_test)))

    cm = confusion_matrix(goal_test, classifier.predict(test_set))
    print('K = %d\n-------------'%K)
    print(pd.DataFrame(cm))
    print('-------------\n\n')

model accuracy : 0.8202
K = 1
-------------
      0    1
0  7136  844
1   782  281
-------------


model accuracy : 0.8567
K = 3
-------------
      0    1
0  7579  401
1   895  168
-------------


model accuracy : 0.8717
K = 5
-------------
      0    1
0  7777  203
1   957  106
-------------


model accuracy : 0.8817
K = 10
-------------
      0   1
0  7935  45
1  1025  38
-------------


model accuracy : 0.8825
K = 20
-------------
      0   1
0  7959  21
1  1042  21
-------------


model accuracy : 0.8826
K = 100
-------------
      0  1
0  7979  1
1  1061  2
-------------


model accuracy : 0.8825
K = 150
-------------
      0  1
0  7980  0
1  1063  0
-------------


model accuracy : 0.8825

# Using Logistic

In [ ]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(random_state = 0)
logistic.fit(train_set, goal_train)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(goal_test, logistic.predict(test_set))
pd.DataFrame(cm)

logistic.score(test_set, goal_test)

# Using Naive Bays

In [25]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(train_set, goal_train)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(goal_test, classifier.predict(test_set))
print(classifier.score(test_set, goal_test))
pd.DataFrame(cm)

0.8524590163934426

    0   1
0  21   6
1   3  31

# Using Decision Tree

In [26]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(random_state=0)
classifier.fit(train_set, goal_train)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(goal_test, classifier.predict(test_set))
print(classifier.score(test_set, goal_test))
pd.DataFrame(cm)

0.7704918032786885

    0   1
0  22   5
1   9  25

# Using Gaussian SVM

In [27]:
from sklearn.svm import SVC
classifier = SVC(kernel ='rbf', random_state = 0)
classifier.fit(train_set, goal_train)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(goal_test, classifier.predict(test_set))
print(classifier.score(test_set, goal_test))
pd.DataFrame(cm)

0.8688524590163934

    0   1
0  21   6
1   2  32

# Using Poly SVM

In [ ]:
#classifier = SVC(kernel='poly', random_state=0)
#classifier.fit(train_set, goal_train)

In [ ]:
#from sklearn.metrics import confusion_matrix
#cm = confusion_matrix(goal_test, classifier.predict(test_set))
#print(classifier.score(test_set, goal_test))
#pd.DataFrame(cm)